### PR TITLE
change tab order in config

### LINKED ISSUE #431: Tab is not jumping to the right place in Mergin Settings window
When I try to insert my username and password, I first enter my username and then press Tab key hoping to jump to the password field, but it does not. I have to use mouse and move and click the cursor inside the password field.

I lose quite a lot of productivity and would much prefer to have the tab key jumping from username field to password field! :)

### PR DESCRIPTION
**Pull request by roya0045**
Proposal to change the tab order.

Fixes #431

### CODE REVIEW

**Comment by roya0045** [comment]
For ref https://doc.qt.io/qt-6/designer-tab-order.html

**Review by PeterPetrik — APPROVED** [review]
LGTM. 

@jozef-budac can you test it please?

**Comment by jozef-budac** [comment]
@PeterPetrik This PR looks ok

**Comment by PeterPetrik** [comment]
Thanks @roya0045 for your commitment!

**Comment by roya0045** [comment]
@PeterPetrik @jozef-budac Thank you for taking the time to check this, this is appreciated!

**Pull request merged**
