### PR TITLE
Snapping settings

### PR DESCRIPTION
**Pull request by alexbruy**
Add Input snapping settings to the QGIS project setting
зображення

Also add a validation for the case when "Follow QGIS snapping" mode is selected but snapping is not enabled in the project.

### CODE REVIEW

**Comment by wonder-sk** [comment]
It would be good to include a link in the GUI to a page where this will be documented in the future :)

**Comment by alexbruy** [comment]
> It would be good to include a link in the GUI to a page where this will be documented in the future :)

We have a place reserved for the link, but it is not clear where it will go. I can insert link using selective sync (https://merginmaps.com/docs/manage/selective_sync/) as an example, but not sure this is a right way to go.

**Comment by PeterPetrik** [comment]
@alex-cit do you know the future link name? or it will be part of some existing page?

**Comment by alex-cit** [comment]
I would reference this: https://merginmaps.com/docs/gis/features/#project-settings its overview of general project settings, including photo quality and selective sync.

**Comment by alexbruy** [comment]
Linked to https://merginmaps.com/docs/gis/features/#project-settings.

**Review by varmar05 — APPROVED** [review]

**Pull request merged**
